name: Step 4

on:
  push:
    branches:
      - my-ghc-extension
    paths:
      - "ghc-extension-js/agent-knowledge/**"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_5_FILE: ".github/steps/5-step.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Find last comment
        id: find-last-comment
        uses: peter-evans/find-comment@v3
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          direction: last

      - name: Update comment - checking work
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          file: exercise-toolkit/markdown-templates/step-feedback/checking-work.md
          edit-mode: replace

      # START: Check practical exercise

      - name: Check agent job description does not use the template
        id: check-agent-job-description
        continue-on-error: true
        run: |            
          job_description=$(<"./ghc-extension-js/agent-knowledge/job-description.md")
          if [[ $job_description =~ "customize the job description" ]]; then
            echo "Job description still uses the template. Please customize it."
            exit 1
          fi

      - name: Check school overview does not use the template
        continue-on-error: true
        id: check-school-overview
        run: |
          school_overview=$(<"./ghc-extension-js/agent-knowledge/school-overview.md")
          if [[ $school_overview =~ "customize the school overview" ]]; then
            echo "School overview still uses the template. Please customize it."
            exit 1
          fi

      - name: Check staff roles does not use the template
        continue-on-error: true
        id: check-staff-roles
        run: |
          staff_roles=$(<"./ghc-extension-js/agent-knowledge/staff-roles.md")
          if [[ $staff_roles =~ "some roles a high school might have" ]]; then
            echo "Staff roles still use the template. Please customize it."
            exit 1
          fi

      # END: Check practical exercise

      - name: Update comment - step results
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          edit-mode: replace
          vars: |
            step_number: 4
            results_table:
              - description: "Agent description updated"
                passed: ${{ steps.check-agent-job-description.outcome == 'success' }}
              - description: "School overview updated"
                passed: ${{ steps.check-school-overview.outcome == 'success' }}
              - description: "Staff roles updated"
                passed: ${{ steps.check-staff-roles.outcome == 'success' }}

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1


  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Create comment - step finished
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 5

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_5_FILE }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 5"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
